# Add a new line to the file for the theme name.

# To use a supported theme, type theme: THEME-NAME, replacing THEME-NAME with the
# name of the theme as shown in the _config.yml of the theme's repository
# (most themes follow a jekyll-theme-NAME naming convention). 
# For a list of supported themes, see "Supported themes" on the GitHub Pages site. 
# For example, to select the Minimal theme, type theme: jekyll-theme-minimal.
# To use any other Jekyll theme hosted on GitHub, type remote_theme: THEME-NAME, 
# replacing THEME-NAME with the name of the theme as shown in the README of the theme's repository.




title: Ebunle Rene
show_downloads: true
theme: jekyll-theme-Architect
